=== FeeB/Dictionary/liste.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT entries (entry+) >
<!ATTLIST entry
           id CDATA #REQUIRED>
<!ELEMENT entry (term, definition, tags*) >
<!ELEMENT tags (tag+)>
<!ELEMENT term (#PCDATA) >
<!ELEMENT definition (#PCDATA) >
<!ELEMENT tag (#PCDATA) >

=== FeeB/Dictionary/liste.xml
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE entries SYSTEM "file:/Users/Fee/Sites/Semesterarbeit_FeeBraun/liste.dtd">
<entries>
    <entry id="1">
        <term>Addition von Binärzahlen</term>
        <definition>Die Addition ist analog zu dem Dezimalsystem. Jedoch wird hier ein Überhang von 1 zur nächst höheren Potenz übertragen, wenn das Ergebnis größer als 2 ist. 0+0=0; 1+0=1; 1+1=0 mit Übertrag</definition>
        <tags>
        	<tag>Zahlensystem</tag>
        	<tag>Binärzahlen</tag>
         	<tag>Rechenart</tag>
       </tags>
    </entry>
    <entry id="2">
        <term>Bestandteile Von-Neumann-Architektur</term>
        <definition>Eine von Neumann-Maschine besteht aus der zentralen Recheneinheit CPU, die wiederum aus ALU und der Steuereinheit besteht. Die ALU bearbeitet Daten, die Steuereinheit koordiniert die zeitlichen Abläufe im Rechner. Durch diese Prozesse werden Befehle  geholt und können anschließend ausgeführt werden.
            Die Steuereinheit hat die Bestandteile Befehlsregister, Befehlsdecoder, Speicheradressregister und Befehlszähler.
            
            Als nächste Komponente der von Neumann-Maschine ist der Speicher zu nennen. Dieser beinhaltet Speicherzellen, die jeweils ein Bit speichern können. Die Speicherzellen werden zu Speicherworten oder Speicherzeilen zusammengefasst.
            
            Zudem gibt es die Ein- und Ausgabe-Einheit, diese Einheit kann mit allem kommunizieren, was "nicht mehr zu dem eigentlichen, universellen Von Neumann Rechner-Konzept gehört". Somit bildet diese Einheit die Schnittstelle zur Außenwelt.
            
            Als letzte Komponente wird der interne Datenweg (Bus) beschrieben. Die wichtigsten Busse sind der Datenbus, der Adressbus und der Steuerbus.
            Der Datenbus überträgt die Daten, die über den Adressbus angefordert wurden. Der Adressbus überträgt ausschließlich Adressen (Speicherplätze vom Speicheranfang bis zum Speicherende). Der Steuerbus übernimmt die Kontrolle über den Bus.
        </definition> 
        <tags>
        	<tag>Architektur</tag>
        	<tag>Von-Neumann</tag>
        </tags>        
    </entry>
    <entry id="3">
        <term>Binärcode</term>
        <definition>Binärcode ist die Gesamtheit aller Codes welche Informationen durch Sequenzen von zwei verschiedenen Symbolen (zum Beispiel 1/0 oder wahr/falsch) dargestellt werden können. Die Bezeichnung leitet sich von der lateinischen Vorsilbe "bi" ab, welche die Bedeutung "zwei" oder "doppelt" hat.
            Vor allem bei der digitalen Verarbeitung von Informationen spielen Binärcodes eine große Rolle, da sie sich durch Spannungswerte sehr leicht abbilden lassen. (Beispiel: Spannung liegt an → logisch 1, Spannung liegt nicht an → logisch 0). Dabei kommen verschiedene Verfahren und Techniken zu Anwendung, die in den einzelne Codes genauer beschrieben sind, gemeinsame Basis bildet jedoch immer die Festlegung auf nur zwei verschiedene Symbole. Entsprechen die beiden Symbole 1/0 bzw. wahr/falsch spricht man in der Informationstechnik von einem Bit.
        </definition>
        <tags>
        	<tag>Binärzahlen</tag>
        	<tag>Zahlensystem</tag>
        </tags>
    </entry>
    <entry id="4">
        <term>Bit</term>
        <definition>Der Begriff Bit (binary digit) wird in der Informatik, der Informationstechnik, der Nachrichtentechnik sowie verwandten Fachgebieten in folgenden Bedeutungen verwendet:
            als Bezeichnung für eine Binärziffer (üblicherweise „0“ und „1“).
            als Maßeinheit für die Datenmenge bei digitaler Speicherung von Daten. Die Datenmenge entspricht in diesem Fall der verwendeten Anzahl von binären Variablen zur Abbildung der Information, kann also nur als ganzzahliges Vielfaches von 1 Bit angegeben werden.
            als Maßeinheit für den Informationsgehalt (siehe auch Shannon, Nit, Ban). Dabei ist 1 Bit der Informationsgehalt, der in einer Auswahl aus zwei gleich wahrscheinlichen Möglichkeiten enthalten ist. Als Informationsgehalt können auch reellwertige Vielfache von 1 Bit auftreten.
        </definition>
        <tags>
        	<tag>Binärzahlen</tag>
        	<tag>Zahlensystem</tag>
        </tags>
    </entry>
    <entry id="5">
        <term>Darstellungsmöglichkeiten Bit</term>
        <definition>1 Bit = 2 Darstellungsmöglichkeiten
            2 Bit = 4 Darstellungsmöglichkeiten
            3 Bit = 16 Darstellungsmöglichkeiten
            4 Bit = 32 Darstellungsmöglichkeiten
            5 Bit = 64 Darstellungsmöglichkeiten
            6 Bit = 128 Darstellungsmöglichkeiten
            usw.
        </definition>
        <tags>
        	<tag>Binärzahlen</tag>
        </tags>
    </entry>
    <entry id="6">
        <term>Hexadezimal</term>
        <definition>Im Hexadezimalsystem (lat.-griech. Mischwort) werden Zahlen in einem Stellenwertsystem zur Basis 16 dargestellt.
            Alternative Bezeichnungen für hexadezimal (von griech. „hexa“ und lat. „decem“) sind hexadekadisch (Griechisch) und sedezimal (Latein). (Falsch hingegen ist der Ausdruck hexagesimal, der synonym zu sexagesimal ist und das Zahlensystem zur Basis 60 bezeichnet.)
            In der Datenverarbeitung wird das Hexadezimalsystem sehr oft verwendet, da es sich hierbei letztlich nur um eine komfortablere Verwaltung des Binärsystems handelt. Die Datenworte bestehen in der Informatik meist aus Oktetten, die statt als achtstellige Binärzahlen auch als nur zweistellige Hexadezimalzahlen dargestellt werden können. Im Gegensatz zum Dezimalsystem eignet sich das Hexadezimalsystem mit seiner Basis als vierte Zweierpotenz (16 = 24) zur einfacheren Notation der Binärzahlen, da stets eine feste Anzahl Zeichen zur Wiedergabe des Datenwortes benötigt wird.
        </definition>
        <tags>
        	<tag>Zahlensystem</tag>
        </tags>
    </entry>
    <entry id="7">
        <term>Multiplikation von Binärzahlen</term>
        <definition>Die Multiplikation wird wie im Dezimalsystem durchgeführt;  die Produkte werden untereinander geschrieben und dann addiert</definition>
        <tags>
        	<tag>Zahlensystem</tag>
        	<tag>Binärzahlen</tag>
         	<tag>Rechenart</tag>
       </tags>
    </entry>
    <entry id="8">
        <term>Subtraktion von Binärzahlen</term>
        <definition>Subtraktion erfolgt mit dem Zweierkomplement: Addition des Zweierkomplement der negativen Zahl</definition>
        <tags>
        	<tag>Zahlensystem</tag>
        	<tag>Binärzahlen</tag>
         	<tag>Rechenart</tag>
       </tags>
    </entry>
    <entry id="9">
        <term>Umrechnung Dezimal in Binär</term>
        <definition>Die umzuwandelnde Zahl wird durch 2 dividiert. Das Ergebnis wird wiederum durch 2 dividiert. Der jeweilige Rest wird als Binärzahl in eine Reihenfolge von rechts nach linkss gebracht</definition>
        <tags>
        	<tag>Umrechnung</tag>
        	<tag>Binärzahlen</tag>
       </tags>
    </entry>
    <entry id="10">
        <term>Universalrechner</term>
        <definition>Die von Neumann Maschine ist ein Universalrechner, weil sie nicht nur für ein spezielles Problem konstruiert wurde, sondern in der Lage ist verschiedene Probleme mit entsprechender Software zu lösen. Dies ist möglich, da die Struktur des Rechners von dem Problem unabhängig ist.</definition>
        <tags>
        	<tag>Architektur</tag>
        </tags>
    </entry>
    <entry id="11">
        <term>Von-Neumann Maschine</term>
        <definition>Die von Neumann Maschine ist ein Universalrechner, weil sie nicht nur für ein spezielles Problem konstruiert wurde, sondern in der Lage ist verschiedene Probleme mit entsprechender Software zu lösen. Dies ist möglich, da die Struktur des Rechners von dem Problem unabhängig ist.</definition>
        <tags>
        	<tag>Architektur</tag>
        	<tag>Von-Neumann</tag>
        </tags>
    </entry>
    <entry id="12">
    	<term>ASCII-Code</term>
    	<definition>American Standard Code for Information Interchange (ASCII, alternativ US-ASCII, oft [æski] ausgesprochen) ist eine 7-Bit-Zeichenkodierung; sie entspricht der US-Variante von ISO 646 und dient als Grundlage für spätere auf mehr Bits basierenden Kodierungen für Zeichensätze.</definition>
    	<tags>
    		<tag>Zeichencodierung</tag>
    	</tags>
    </entry>
    <entry id="13">
    	<term>Unicode</term>
    	<definition>Unicode [ˈjuːnɪkoʊd] ist ein internationaler Standard, in dem langfristig für jedes sinntragende Schriftzeichen oder Textelement aller bekannten Schriftkulturen und Zeichensysteme ein digitaler Code festgelegt wird. Ziel ist es, die Verwendung unterschiedlicher und inkompatibler Kodierungen in verschiedenen Ländern oder Kulturkreisen zu beseitigen. Unicode wird laufend um Zeichen weiterer Schriftsysteme ergänzt. ISO 10646 ist die von ISO verwendete, praktisch bedeutungsgleiche Bezeichnung des Unicode-Zeichensatzes; er wird dort als Universal Character Set (UCS) bezeichnet.</definition>
    	<tags>
    		<tag>Zeichencodierung</tag>
    	</tags>
    </entry>
    <entry id="14">
    	<term>Logikgatter</term>
    	<definition>Ein Logikgatter oder Gatter (engl. gate) vollzieht in der technischen Informatik eine logische Auswertung von Eingangssignalen an einer Schaltung der Digitaltechnik. Dabei werden an einem oder mehreren Eingängen logische Zustände angelegt – gemeinhin als „0” oder „1” interpretiert –, die mit logischen Operatoren wie UND, ODER oder NICHT in ein einziges logisches Ergebnis umgewandelt werden. Je nach Realisierung der Gatter können die Signale in Form von Spannungspegeln, Druck oder Bewegung von Gasen oder Flüssigkeiten, oder weiterem vorliegen. Dabei wird meistens der jeweils höhere Pegel als "1" - logisch Wahr - und der niedrigere als "0" - logisch Falsch betrachtet.</definition>
    	<tags>
    		<tag>technische Informatik</tag>
    		<tag>Schaltung</tag>
    	</tags>
    </entry>
    <entry id="15">
    	<term>NOT-Gatter</term>
